### ISSUE TITLE
Tooltip search bug

### ISSUE THREAD

**Issue by ProTriforcer** [CleanroomMC/HadEnoughItems#42]
If i start the game, load a world and search for `#Fe`, for example, only a few items that have `Fe` in their tooltip are shown. 
![image](https://user-images.githubusercontent.com/25221392/206930959-b2940efb-7ac3-417c-abec-3f8774f25e44.png)
If i then restart the game with `#Fe` still in the search box or change some HEI configs that reload search trees, tooltip search works properly.
![image](https://user-images.githubusercontent.com/25221392/206931340-42e80818-5a9d-4cbd-b5a5-535f42a18f4c.png)

Disabling `Search Advanced Tooltips` and `Search Stripped Diacritics` shows more items, but still not all of them. 
This isn't just a GTCEu issue, since items and tooltips from other mods, such as "Iron **Fe**nce" glass from Chisel, are affected too.

Encountered in Nomifactory CEu with HadEnoughItems_1.12.2-4.24.2.jar

**Comment by Krutoy242** [comment]
I found this problem too, long time ago.

Also i foung that disable and enable `Search Advanced Tooltips` options change number of items could be found this way. Sometimes it shows more, sometimes less.

**Comment by Krutoy242** [comment]
This issue still actual!

Since E2E-Extended modpack using tooltips as "tags" for searching items, such as `#generator` or `#voidMiner`, fix of this issue really wanted.

**Comment by ZHAY10086** [comment]
> This issue still actual!

It's caused by `Faster Background Startup` option from `Universal Tweaks`.

**Comment by Krutoy242** [comment]
> It's caused by `Faster Background Startup` option from `Universal Tweaks`.

Thank you for the hint! I will try to check this out.

**Comment by Wizzerinus** [comment]
ran into this awhile ago as well: https://github.com/TeamDimensional/Dimension-Gateway/commit/30a718de718821096188dac5ecefe1162ab982aa

**Comment by Krutoy242** [comment]
> It's caused by `Faster Background Startup` option from `Universal Tweaks`.

No, this actually wont help. Everyone still experience the bug https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/416

**Comment by Krutoy242** [comment]
The issue with tooltip search is still partially actual.

There is an example:

Tooltip search is set to `require_prefix`:
![image](https://github.com/user-attachments/assets/609c5291-63b6-446e-9f9b-23430be96dc5)

But still not all items that **have** tooltip actually considering as having tooltip:
![image](https://github.com/user-attachments/assets/7af855bf-9399-4a66-8def-bfa464e0d17c)

![image](https://github.com/user-attachments/assets/b9ffcee7-62b9-4430-9f9b-97f18679542c)

I can open new issue if needed.

This issue is notable in E2EE, since modpack have huge variations of options such as Tanks, Miners, Generators and such. If players would be able to search those categories, it would be very handy!
